### ISSUE TITLE
в утп только в веб-форме добавить 2 колонки с ИАК

### ISSUE THREAD

**Issue by Bukharovsi** [Bukharovsi/curriculum#88]
Добавить 2 колонки - первая "кол-во часов на одного члена ИАК", вторая "Общее количество часов на всех членов ИАК".
первая - вбивается вручную, 
вторая - произведение первой на количество преподавателей (не редактируемо вручную)

**Comment by KuznetsovVlad** [comment]
Только веб формы касается? Выгрузка в файл не нужна, От этих колонок зависит вычисление **всего часов** #89 Если так то получиться что в файле и на форме будут разные значения. Так же если добавим еще две колонки, надо будет подумать что делать с местом, а то там очень много колоночек уже.

**Comment by Bukharovsi** [comment]
нет и в файле тоже. Переговорили с куратором, сейчас опишу в хедере тикета

**Comment by Bukharovsi** [comment]
переформулирую в другом тикете
